name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        shell: pwsh
        run: choco pack

      - name: ls
        shell: pwsh
        run: ls *.nupkg

      - name: Publish
        shell: pwsh
        run: |
          # Read the contents of a .nuspec file
          $xmlContent = Get-Content -Path faforever.nuspec -Raw

          # Parsing XML content
          [xml]$xml = $xmlContent

          # Extract the version number
          $version = $xml.package.metadata.version

          # Output version number
          Write-Output "Package version: $version"

          $packageFile = "faforever.$version.nupkg"

          if (test-path -Path "$packageFile") {
            choco push "$packageFile" --api-key "$env:API_KEY" --source https://push.chocolatey.org/
            Write-Output "The file($packageFile) was removed successfully."
          } else {
            Write-Output "The specified file($packageFile) was not found."
          }
        env:
          API_KEY: ${{ secrets.API_KEY }}